const prefix = 'serviceInstances';

// UI actions
export const DELETE_SERVICE_INSTANCE_TRIGGER = `${prefix}/DELETE_SERVICE_INSTANCE_TRIGGER`;
export const EDIT_SERVICE_INSTANCE_FIELD_CHANGE = `${prefix}/EDIT_SERVICE_INSTANCE_FIELD_CHANGE`;

// API actions
export const LOAD_SERVICE_INSTANCES = `${prefix}/LOAD_SERVICE_INSTANCES`;
export const LOAD_SERVICE_INSTANCES_SUCCESS = `${prefix}/LOAD_SERVICE_INSTANCES_SUCCESS`;
export const LOAD_SERVICE_INSTANCES_FAIL = `${prefix}/LOAD_SERVICE_INSTANCES_FAIL`;

export const LOAD_SERVICE_INSTANCE_CHOICES = `${prefix}/LOAD_SERVICE_INSTANCE_CHOICES`;
export const LOAD_SERVICE_INSTANCE_CHOICES_SUCCESS = `${prefix}/LOAD_SERVICE_INSTANCE_CHOICES_SUCCESS`;
export const LOAD_SERVICE_INSTANCE_CHOICES_FAIL = `${prefix}/LOAD_SERVICE_INSTANCE_CHOICES_FAIL`;

export const LOAD_SINGLE_SERVICE_INSTANCE = `${prefix}/LOAD_SINGLE_SERVICE_INSTANCE`;
export const LOAD_SINGLE_SERVICE_INSTANCE_SUCCESS = `${prefix}/LOAD_SINGLE_SERVICE_INSTANCE_SUCCESS`;
export const LOAD_SINGLE_SERVICE_INSTANCE_FAIL = `${prefix}/LOAD_SINGLE_SERVICE_INSTANCE_FAIL`;

export const EDIT_SERVICE_INSTANCE = `${prefix}/EDIT_SERVICE_INSTANCE`;
export const EDIT_SERVICE_INSTANCE_SUCCESS = `${prefix}/EDIT_SERVICE_INSTANCE_SUCCESS`;
export const EDIT_SERVICE_INSTANCE_FAIL = `${prefix}/EDIT_SERVICE_INSTANCE_FAIL`;

export const CREATE_SERVICE_INSTANCE = `${prefix}/CREATE_SERVICE_INSTANCE`;
export const CREATE_SERVICE_INSTANCE_SUCCESS = `${prefix}/CREATE_SERVICE_INSTANCE_SUCCESS`;
export const CREATE_SERVICE_INSTANCE_FAIL = `${prefix}/CREATE_SERVICE_INSTANCE_FAIL`;

export const DELETE_SERVICE_INSTANCE = `${prefix}/DELETE_SERVICE_INSTANCE`;
export const DELETE_SERVICE_INSTANCE_SUCCESS = `${prefix}/DELETE_SERVICE_INSTANCE_SUCCESS`;
export const DELETE_SERVICE_INSTANCE_FAIL = `${prefix}/DELETE_SERVICE_INSTANCE_FAIL`;
