const prefix = 'service-orders';

// UI actions
export const LIST_FILTERS_CHANGE = `${prefix}/LIST_FILTERS_CHANGE`;
export const NEW_SERVICE_ORDER_FORM_CHANGE = `${prefix}/NEW_SERVICE_ORDER_FORM_CHANGE`;
export const EDIT_SERVICE_ORDER_FORM_CHANGE = `${prefix}/EDIT_SERVICE_ORDER_FORM_CHANGE`;
export const DELETE_SERVICE_ORDER_TRIGGER = `${prefix}/DELETE_SERVICE_ORDER_TRIGGER`;
export const PAGE_CHANGE = `${prefix}/PAGE_CHANGE`;
export const SERVICE_GROUP_EDIT = `${prefix}/SERVICE_GROUP_EDIT`;

// API actions
export const LOAD_SERVICE_ORDERS = `${prefix}/LOAD_SERVICE_ORDERS`;
export const LOAD_SERVICE_ORDERS_SUCCESS = `${prefix}/LOAD_SERVICE_ORDERS_SUCCESS`;
export const LOAD_SERVICE_ORDERS_FAIL = `${prefix}/LOAD_SERVICE_ORDERS_FAIL`;

export const LOAD_SERVICE_ORDER_CHOICES = `${prefix}/LOAD_SERVICE_ORDER_CHOICES`;
export const LOAD_SERVICE_ORDER_CHOICES_SUCCESS = `${prefix}/LOAD_SERVICE_ORDER_CHOICES_SUCCESS`;
export const LOAD_SERVICE_ORDER_CHOICES_FAIL = `${prefix}/LOAD_SERVICE_ORDER_CHOICES_FAIL`;

export const LOAD_SINGLE_SERVICE_ORDER = `${prefix}/LOAD_SINGLE_SERVICE_ORDER`;
export const LOAD_SINGLE_SERVICE_ORDER_SUCCESS = `${prefix}/LOAD_SINGLE_SERVICE_ORDER_SUCCESS`;
export const LOAD_SINGLE_SERVICE_ORDER_FAIL = `${prefix}/LOAD_SINGLE_SERVICE_ORDER_FAIL`;

export const EDIT_SERVICE_ORDER = `${prefix}/EDIT_SERVICE_ORDER`;
export const EDIT_SERVICE_ORDER_SUCCESS = `${prefix}/EDIT_SERVICE_ORDER_SUCCESS`;
export const EDIT_SERVICE_ORDER_FAIL = `${prefix}/EDIT_SERVICE_ORDER_FAIL`;

export const CREATE_SERVICE_ORDER = `${prefix}/CREATE_SERVICE_ORDER`;
export const CREATE_SERVICE_ORDER_SUCCESS = `${prefix}/CREATE_SERVICE_ORDER_SUCCESS`;
export const CREATE_SERVICE_ORDER_FAIL = `${prefix}/CREATE_SERVICE_ORDER_FAIL`;

export const DELETE_SERVICE_ORDER = `${prefix}/DELETE_SERVICE_ORDER`;
export const DELETE_SERVICE_ORDER_SUCCESS = `${prefix}/DELETE_SERVICE_ORDER_SUCCESS`;
export const DELETE_SERVICE_ORDER_FAIL = `${prefix}/DELETE_SERVICE_ORDER_FAIL`;
