const prefix = 'serviceGroups';

// UI actions
export const DELETE_SERVICE_GROUP_TRIGGER = `${prefix}/DELETE_SERVICE_GROUP_TRIGGER`;
export const EDIT_SERVICE_GROUP_FIELD_CHANGE = `${prefix}/EDIT_SERVICE_GROUP_FIELD_CHANGE`;

// API actions
export const LOAD_SERVICE_GROUPS = `${prefix}/LOAD_SERVICE_GROUPS`;
export const LOAD_SERVICE_GROUPS_SUCCESS = `${prefix}/LOAD_SERVICE_GROUPS_SUCCESS`;
export const LOAD_SERVICE_GROUPS_FAIL = `${prefix}/LOAD_SERVICE_GROUPS_FAIL`;

export const LOAD_SERVICE_GROUP_CHOICES = `${prefix}/LOAD_SERVICE_GROUP_CHOICES`;
export const LOAD_SERVICE_GROUP_CHOICES_SUCCESS = `${prefix}/LOAD_SERVICE_GROUP_CHOICES_SUCCESS`;
export const LOAD_SERVICE_GROUP_CHOICES_FAIL = `${prefix}/LOAD_SERVICE_GROUP_CHOICES_FAIL`;

export const LOAD_SINGLE_SERVICE_GROUP = `${prefix}/LOAD_SINGLE_SERVICE_GROUP`;
export const LOAD_SINGLE_SERVICE_GROUP_SUCCESS = `${prefix}/LOAD_SINGLE_SERVICE_GROUP_SUCCESS`;
export const LOAD_SINGLE_SERVICE_GROUP_FAIL = `${prefix}/LOAD_SINGLE_SERVICE_GROUP_FAIL`;

export const EDIT_SERVICE_GROUP = `${prefix}/EDIT_SERVICE_GROUP`;
export const EDIT_SERVICE_GROUP_SUCCESS = `${prefix}/EDIT_SERVICE_GROUP_SUCCESS`;
export const EDIT_SERVICE_GROUP_FAIL = `${prefix}/EDIT_SERVICE_GROUP_FAIL`;

export const CREATE_SERVICE_GROUP = `${prefix}/CREATE_SERVICE_GROUP`;
export const CREATE_SERVICE_GROUP_SUCCESS = `${prefix}/CREATE_SERVICE_GROUP_SUCCESS`;
export const CREATE_SERVICE_GROUP_FAIL = `${prefix}/CREATE_SERVICE_GROUP_FAIL`;

export const DELETE_SERVICE_GROUP = `${prefix}/DELETE_SERVICE_GROUP`;
export const DELETE_SERVICE_GROUP_SUCCESS = `${prefix}/DELETE_SERVICE_GROUP_SUCCESS`;
export const DELETE_SERVICE_GROUP_FAIL = `${prefix}/DELETE_SERVICE_GROUP_FAIL`;
