const prefix = 'doc-templates';

// UI actions
export const LIST_FILTERS_CHANGE = `${prefix}/LIST_FILTERS_CHANGE`;
export const NEW_DOCUMENT_TEMPLATE_FORM_CHANGE = `${prefix}/NEW_DOCUMENT_TEMPLATE_FORM_CHANGE`;
export const EDIT_DOCUMENT_TEMPLATE_FORM_CHANGE = `${prefix}/EDIT_DOCUMENT_TEMPLATE_FORM_CHANGE`;
export const DELETE_DOCUMENT_TEMPLATE_TRIGGER = `${prefix}/DELETE_DOCUMENT_TEMPLATE_TRIGGER`;

// API actions
export const LOAD_DOCUMENT_TEMPLATES = `${prefix}/LOAD_DOCUMENT_TEMPLATES`;
export const LOAD_DOCUMENT_TEMPLATES_SUCCESS = `${prefix}/LOAD_DOCUMENT_TEMPLATES_SUCCESS`;
export const LOAD_DOCUMENT_TEMPLATES_FAIL = `${prefix}/LOAD_DOCUMENT_TEMPLATES_FAIL`;

export const LOAD_DOCUMENT_TEMPLATE_CHOICES = `${prefix}/LOAD_DOCUMENT_TEMPLATE_CHOICES`;
export const LOAD_DOCUMENT_TEMPLATE_CHOICES_SUCCESS = `${prefix}/LOAD_DOCUMENT_TEMPLATE_CHOICES_SUCCESS`;
export const LOAD_DOCUMENT_TEMPLATE_CHOICES_FAIL = `${prefix}/LOAD_DOCUMENT_TEMPLATE_CHOICES_FAIL`;

export const LOAD_SINGLE_DOCUMENT_TEMPLATE = `${prefix}/LOAD_SINGLE_DOCUMENT_TEMPLATE`;
export const LOAD_SINGLE_DOCUMENT_TEMPLATE_SUCCESS = `${prefix}/LOAD_SINGLE_DOCUMENT_TEMPLATE_SUCCESS`;
export const LOAD_SINGLE_DOCUMENT_TEMPLATE_FAIL = `${prefix}/LOAD_SINGLE_DOCUMENT_TEMPLATE_FAIL`;

export const EDIT_DOCUMENT_TEMPLATE = `${prefix}/EDIT_DOCUMENT_TEMPLATE`;
export const EDIT_DOCUMENT_TEMPLATE_SUCCESS = `${prefix}/EDIT_DOCUMENT_TEMPLATE_SUCCESS`;
export const EDIT_DOCUMENT_TEMPLATE_FAIL = `${prefix}/EDIT_DOCUMENT_TEMPLATE_FAIL`;

export const CREATE_DOCUMENT_TEMPLATE = `${prefix}/CREATE_DOCUMENT_TEMPLATE`;
export const CREATE_DOCUMENT_TEMPLATE_SUCCESS = `${prefix}/CREATE_DOCUMENT_TEMPLATE_SUCCESS`;
export const CREATE_DOCUMENT_TEMPLATE_FAIL = `${prefix}/CREATE_DOCUMENT_TEMPLATE_FAIL`;

export const DELETE_DOCUMENT_TEMPLATE = `${prefix}/DELETE_DOCUMENT_TEMPLATE`;
export const DELETE_DOCUMENT_TEMPLATE_SUCCESS = `${prefix}/DELETE_DOCUMENT_TEMPLATE_SUCCESS`;
export const DELETE_DOCUMENT_TEMPLATE_FAIL = `${prefix}/DELETE_DOCUMENT_TEMPLATE_FAIL`;
